### PR TITLE
added paragraph

### PR DESCRIPTION
**Pull request by webdevhamid**
I have added a paragraph below the heading.

Here is the code:

```
    <p>
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum, sed? At, incidunt quaerat.
      Velit libero sequi perspiciatis quia magni aut.
    </p>
```

Also, created a style.css file and colored the paragraph.

```
p {
  color: tomato;
}
```

I would be pleased if you accept my pull request.

Thanks,
Abdul Hamid

### CODE REVIEW

**Review by developerhamid1 — COMMENTED** [review]
Looks everything nice. Good job.

**Comment by webdevhamid** [comment]
Then, Please merge my code into your codebase.

Thanks.

**Comment by webdevhamid** [comment]
Thanks for giving me this opportunity to contribute to the open-source community.

**Comment by developerhamid1** [comment]
My pleasure :)

**Pull request merged**
